from __future__ import annotations

import pandas as pd


class BusinessState:
    """
    Shared state object used across the entire ProfitPilot workflow.

    It stores the dataset, schema, audit results, user queries,
    intermediate agent outputs, visualizations, reports,
    conversation history, and errors.
    """

    def __init__(self) -> None:
        self.reset()

    # ------------------------------------------------------------------ #

    def reset(self) -> None:
        """
        Reset the state for a new analysis session.
        """

        # Dataset
        self.dataframe: pd.DataFrame | None = None
        self.schema: dict | None = None
        self.audit_report: dict | None = None

        # User Input
        self.user_query: str = ""

        # Agent Outputs
        self.agent_outputs: dict = {}

        # Visualizations
        self.charts: list = []

        # Final Report
        self.final_report: str = ""

        # Conversation History
        self.chat_history: list = []

        # Metadata
        self.metadata: dict = {}

        # Errors
        self.error_log: list[str] = []

    # ------------------------------------------------------------------ #

    def set_dataset(
        self,
        dataframe: pd.DataFrame,
        schema: dict,
        audit_report: dict
    ) -> None:
        """
        Store dataset and its metadata.
        """

        self.dataframe = dataframe
        self.schema = schema
        self.audit_report = audit_report

    # ------------------------------------------------------------------ #

    def set_user_query(self, query: str) -> None:
        """
        Store the latest user query.
        """

        self.user_query = query

    # ------------------------------------------------------------------ #

    def add_agent_output(
        self,
        agent_name: str,
        output
    ) -> None:
        """
        Store the output generated by an agent.
        """

        self.agent_outputs[agent_name] = output

    # ------------------------------------------------------------------ #

    def add_chart(self, chart) -> None:
        """
        Store generated visualizations.
        """

        self.charts.append(chart)

    # ------------------------------------------------------------------ #

    def set_final_report(self, report: str) -> None:
        """
        Store the final generated report.
        """

        self.final_report = report

    # ------------------------------------------------------------------ #

    def add_chat_message(
        self,
        role: str,
        message: str
    ) -> None:
        """
        Store conversation history.
        """

        self.chat_history.append(
            {
                "role": role,
                "message": message
            }
        )

    # ------------------------------------------------------------------ #

    def add_error(self, error: str) -> None:
        """
        Store an error message.
        """

        self.error_log.append(error)